lab03/encuesta/urls.py
from django.urls import path

from . import views

app_name = 'encuesta'

urlpatterns = [
    path('', views.index,name='index'),
    path('<int:pregunta_id>/',views.detalle,name='detalle'),
    path('<int:pregunta_id>/votar',views.votar,name='votar')
]

lab03/lab03/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('encuesta/', include('encuesta.urls')),
    path('admin/', admin.site.urls),
]

lab03/encuesta/models.py
from django.db import models

# Create your models here.
class Pregunta(models.Model):
    pregunta_texto = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

class Opcion(models.Model):
    pregunta = models.ForeignKey(Pregunta, on_delete=models.CASCADE)
    opcion_texto = models.CharField(max_length=200)
    votos = models.IntegerField(default=0)

lab03/ventas/models.py
from django.db import models

# Create your models here.
class Direccion(models.Model):
    calle = models.CharField(max_length=100)
    numero = models.IntegerField()
    comuna = models.CharField(max_length=100)
    ciudad = models.CharField(max_length=100)

class Proveedor(models.Model):
    codigo = models.IntegerField(unique=True)
    nombre = models.CharField(max_length=200)
    direccion = models.ForeignKey(Direccion, on_delete=models.CASCADE)
    telefono = models.IntegerField()
    pagina_web = models.URLField()

class Cliente(models.Model):
    codigo = models.IntegerField(unique=True)
    nombre = models.CharField(max_length=200)
    direccion = models.ForeignKey(Direccion, on_delete=models.CASCADE)
    telefonos = models.ManyToManyField('Telefono')

class Telefono(models.Model):
    numero = models.IntegerField()

class Categoria(models.Model):
    nombre = models.CharField(max_length=200)
    descripcion = models.TextField()

class Producto(models.Model):
    identificador = models.CharField(max_length=50, unique=True)
    nombre = models.CharField(max_length=200)
    precio_actual = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.IntegerField()
    proveedor = models.ForeignKey(Proveedor, on_delete=models.CASCADE)
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)

class Venta(models.Model):
    numero_factura = models.IntegerField(unique=True)
    fecha = models.DateTimeField(auto_now_add=True)
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    descuento = models.DecimalField(max_digits=5, decimal_places=2)
    monto_final = models.DecimalField(max_digits=10, decimal_places=2)

class VentaDetalle(models.Model):
    venta = models.ForeignKey(Venta, on_delete=models.CASCADE)
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    precio = models.DecimalField(max_digits=10, decimal_places=2)
    cantidad = models.IntegerField()
    monto_total = models.DecimalField(max_digits=10, decimal_places=2)
    

lab03/encuesta/views.py
from django.shortcuts import render
from .models import Pregunta


# Create your views here.
def index(request):
    latest_question_list = Pregunta.objects.order_by('-pub_date')[:5]
    context = {
        'latest_question_list':latest_question_list
    }
    return render(request,'encuesta/index.html',context)


def detalle(request, pregunta_id):
    pregunta = Pregunta.objects.get(pk=pregunta_id)
    context = {
        'pregunta': pregunta
    }

    return render(request, 'encuesta/detalle.html', context)


def votar(request,pregunta_id):
    pregunta = Pregunta.objects.get(pk=pregunta_id)
    opcionSeleccionada = pregunta.opcion_set.get(pk=request.POST['opcion'])
    opcionSeleccionada.votos += 1
    opcionSeleccionada.save()
    context = {
        'pregunta':pregunta
    }
    return render(request,'encuesta/resultados.html',context)

lab03/ventas/views.py
from django.shortcuts import render

# Create your views here.

lab03/encuesta/templates/encuesta/detalle.html
<h1>{{ pregunta.pregunta_texto }}</h1>

<form action="{% url 'encuesta:votar' pregunta.id %}" method="post">
    {% csrf_token %}
    {% for opcion in pregunta.opcion_set.all %}
        <input type="radio" name="opcion" id="opcion{{ forloop.counter }}" value="{{ opcion.id}}">
        <label for="opcion{{forloop.counter }}">{{ opcion.opcion_texto }}</label><br>
    {% endfor %}
    <input type="submit" value="votar">
</form>
<a href="{% url 'encuesta:index' %}">Ver Preguntas</a>

lab03/encuesta/templates/encuesta/index.html
<h1>Encuesta</h1>
{% if latest_question_list %}
    <ul>
        {% for pregunta in latest_question_list %}
            <li>
                <a href="/encuesta/{{pregunta.id}}">
                    {{pregunta.pregunta_texto}}
                </a>
            </li>
        {% endfor %}
    </ul>
{% else %}
    <p>No hay registros</p>
{% endif %}

lab03/encuesta/templates/encuesta/resultados.html
<h1>{{ pregunta.pregunta_texto }}</h1>
<ul>
    {%for opcion in pregunta.opcion_set.all %}
        <li>{{opcion.opcion_texto }} -- {{opcion.votos }} voto{{ opcion.votos|pluralize }}</li>
    {% endfor %}
</ul>

<a href="{% url 'encuesta:detalle' pregunta.id %}">Votar de nuevo</a>
<a href="{% url 'encuesta:index' %}">Ver Preguntas</a>